@startuml

skinparam monochrome true

package "persistence"

  class MongoDBArticleRepository

  class MongoDBArticleFinder

  class MongoDBArticleCounter

  MongoDBArticleRepository ---|> model.ArticleRepository
  MongoDBArticleFinder ---|> model.ArticleFinder
  MongoDBArticleCounter ---|> model.ArticleCounter
  MongoDBArticleRepository --> MongoDBArticleFinder
  MongoDBArticleRepository --> MongoDBArticleCounter

end package

@enduml